version: '3'
services:
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - 6379:6379

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:4
    ports:
      - 27017:27017

  api-heroes-mongodb:
    container_name: api-heroes-mongodb
    volumes:
      - ./nodejs-with-mongodb-api-example:/src

    build:
      context: ./nodejs-with-mongodb-api-example
    ports:
      - 4000:3000
    environment:
      MONGO_URL: mongodb
      PORT: 3000

    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis

  api-heroes-postgres:
    container_name: api-heroes-postgres
    build:
      context: ./nodejs-with-postgres-api-example
    ports:
      - 3000:3000

    environment:
      POSTGRES_HOST: postgres:mysecretpassword@postgres:5432
      PORT: 3000

    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: heroes
